"""
main.py

FastAPI application — the real backend for the Code Review tool.

Run with:
    uvicorn main:app --reload

Exposes:
    GET  /health      → liveness check
    POST /api/review  → code review endpoint
    GET  /docs        → Swagger UI (auto-generated by FastAPI)

Prompt:
    The active system prompt lives in prompts.py — iterate there, not here.

AI path:  calls the GitHub Models API (OpenAI-compatible) via the openai SDK;
          falls back to rule-based heuristics if the call fails for any reason.
Fallback: rule-based mock — see FALLBACK REVIEW LOGIC section below.
          Real Pylint/ESLint execution is a separate, later task.
"""

import asyncio
import json
import logging
import os
import subprocess
import tempfile
import uuid
from pathlib import Path

from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from groq import Groq

from prompts import build_system_prompt_with_rag
from rag.retriever import retrieve
from schemas import Issue, ReviewRequest, ReviewResponse, UsageResponse
from logging_config import setup_logging, correlation_id_var

# ---------------------------------------------------------------------------
# Startup
# ---------------------------------------------------------------------------

load_dotenv()  # reads GITHUB_TOKEN (and any other vars) from .env

# Set up structured JSON logging (stdout-only)
setup_logging()
log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Usage Statistics
# ---------------------------------------------------------------------------

_usage_stats = {
    "total_requests": 0,
    "ai_requests": 0,
    "fallback_requests": 0,
    "total_prompt_tokens": 0,
    "total_completion_tokens": 0,
    "total_tokens": 0,
}

# ---------------------------------------------------------------------------
# App setup
# ---------------------------------------------------------------------------

app = FastAPI(
    title="Code Review API",
    description="Accepts code snippets and returns structured review feedback.",
    version="0.3.0",
)

# Allow the Vite dev server to call this API directly (CORS).
# In production, tighten this to the deployed frontend origin.
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:5173",   # Vite default dev port
        "http://127.0.0.1:5173",
    ],
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ---------------------------------------------------------------------------
# GitHub Models client (OpenAI-compatible)
# ---------------------------------------------------------------------------

# Initialised once at startup — reads GROQ_API_KEY from the environment.
_ai_client = Groq(
    api_key=os.environ.get("GROQ_API_KEY") or "gsk_dummy_key_for_testing_and_fallback_only",
)

_AI_MODEL = "llama-3.3-70b-versatile"

# The active system prompt is defined in prompts.py — edit it there.


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def map_severity(category: str, engine: str) -> str:
    """
    Map raw linter category from Pylint or ESLint to canonical "bug" or "style" severity.
    """
    cat = category.strip().lower()
    eng = engine.strip().lower()

    if eng == "pylint":
        # Pylint categories can be full names (e.g. 'error') or single letters (e.g. 'E')
        mapping = {
            "error": "bug",
            "e": "bug",
            "fatal": "bug",
            "f": "bug",
            "warning": "style",
            "w": "style",
            "convention": "style",
            "c": "style",
            "refactor": "style",
            "r": "style",
        }
        if cat not in mapping:
            raise KeyError(f"Unknown pylint category: {category}")
        return mapping[cat]

    elif eng == "eslint":
        # ESLint severity: 2 (error) -> bug; 1 (warning) -> style
        mapping = {
            "2": "bug",
            "error": "bug",
            "1": "style",
            "warning": "style",
            "warn": "style",
        }
        if cat not in mapping:
            raise KeyError(f"Unknown eslint category: {category}")
        return mapping[cat]
    else:
        raise ValueError(f"Unknown engine: {engine}")


def validate_input_length(code: str) -> bool:
    """
    Validate that the code does not exceed 500 lines or 10,000 characters.
    """
    line_count = len(code.splitlines())
    char_count = len(code)
    return line_count <= 500 and char_count <= 10000


def validate_ai_response(parsed_data: dict) -> list[Issue]:
    """
    Validate the structure and contents of parsed AI response, returning validated Issue objects.
    Raises ValueError on any schema validation failure.
    """
    raw_issues = parsed_data.get("issues")
    if not isinstance(raw_issues, list):
        raise ValueError("AI response 'issues' is not a list")

    if len(raw_issues) > 20:
        raise ValueError(f"AI response returned {len(raw_issues)} issues, which exceeds the limit of 20")

    validated_issues = []
    for item in raw_issues:
        if not isinstance(item, dict):
            raise ValueError("AI response issue item is not a dictionary")

        severity = item.get("severity")
        title = item.get("title")
        explanation = item.get("explanation")
        fix = item.get("fix")

        if severity not in ("bug", "style"):
            raise ValueError(f"AI response issue has invalid severity: {severity!r}")

        if not isinstance(title, str) or not title.strip() or len(title) > 300:
            raise ValueError("AI response issue has invalid, empty, or too long title")

        if not isinstance(explanation, str) or not explanation.strip() or len(explanation) > 300:
            raise ValueError("AI response issue has invalid, empty, or too long explanation")

        if fix is not None:
            if not isinstance(fix, str) or len(fix) > 300:
                raise ValueError("AI response issue has invalid or too long fix suggestion")

        validated_issues.append(
            Issue(
                severity=severity,
                title=title.strip(),
                explanation=explanation.strip(),
                fix=fix.strip() if fix else None
            )
        )
    return validated_issues


def _call_ai(code: str, language: str) -> list[Issue]:
    """
    Call the GitHub Models API and parse the structured response.

    Retrieves relevant style-guide chunks via RAG before calling the model,
    and injects them into the system prompt as grounding context for style
    issue explanations. Bug detection is unaffected by this context.

    Returns a list of Issue objects on success.
    Raises any exception on failure — callers are responsible for catching.
    """
    # ── RAG retrieval ─────────────────────────────────────────────────────────
    # Retrieve top-2 style-guide chunks for the submitted code.
    # Purely local (no API call) — fails silently if model unavailable.
    rag_chunks = retrieve(code, language, top_k=2)
    if rag_chunks:
        log.debug(
            "RAG retrieved %d chunk(s) for language=%s",
            len(rag_chunks), language,
            extra={
                "event": "rag_retrieval_success",
                "language": language,
                "chunks_count": len(rag_chunks),
                "chunks": [{"label": c["label"], "score": c["score"], "text_snippet": c["text"][:80]} for c in rag_chunks]
            }
        )
    else:
        log.debug(
            "RAG: no chunks retrieved for language=%s",
            language,
            extra={
                "event": "rag_retrieval_empty",
                "language": language
            }
        )

    # ── Deliberate AI failure hook for testing fallback path ──────────────────
    if "TRIGGER_FALLBACK" in code:
        raise ValueError("Forced AI review failure (TRIGGER_FALLBACK hook)")

    # ── AI call ───────────────────────────────────────────────────────────────
    response = _ai_client.chat.completions.create(
        model=_AI_MODEL,
        max_tokens=1024,
        messages=[
            {"role": "system", "content": build_system_prompt_with_rag(language, rag_chunks)},
            {"role": "user",   "content": code},
        ],
    )

    raw_text = response.choices[0].message.content.strip()
    log.debug(
        "AI raw response received",
        extra={
            "event": "ai_raw_response",
            "raw_response": raw_text
        }
    )

    # Track usage totals
    if hasattr(response, "usage") and response.usage:
        _usage_stats["total_prompt_tokens"] += getattr(response.usage, "prompt_tokens", 0)
        _usage_stats["total_completion_tokens"] += getattr(response.usage, "completion_tokens", 0)
        _usage_stats["total_tokens"] += getattr(response.usage, "total_tokens", 0)

    # Strip markdown code fences if the model wraps its JSON in them
    if raw_text.startswith("```"):
        raw_text = raw_text.split("```")[1]
        if raw_text.startswith("json"):
            raw_text = raw_text[4:]
        raw_text = raw_text.strip()

    parsed = json.loads(raw_text)  # raises JSONDecodeError if malformed

    # Validate shape: must have an "issues" list of dicts with required keys.
    return validate_ai_response(parsed)


def _fallback_issues(code: str, language: str) -> list[Issue]:
    """
    Execute real linters via subprocess (Pylint for python, ESLint for javascript)
    and parse their output.
    """
    if language not in ("python", "javascript"):
        log.warning(
            "Unsupported language for fallback linter",
            extra={
                "event": "fallback_unsupported_language",
                "language": language
            }
        )
        return []

    issues: list[Issue] = []

    # Create a secure temporary directory
    with tempfile.TemporaryDirectory() as tmpdir:
        tmp_path = Path(tmpdir)

        if language == "python":
            # Write Python code to a temp file
            code_file = tmp_path / "snippet.py"
            code_file.write_text(code, encoding="utf-8")

            try:
                # Run pylint with --output-format=json, --persistent=n (disabled cache), and --score=n
                cmd = ["pylint", "--output-format=json", "--persistent=n", "--score=n", str(code_file)]
                res = subprocess.run(cmd, capture_output=True, text=True, timeout=5, shell=False)

                # Pylint returns non-zero codes on style/lint findings. That is expected.
                # Only raise if pylint crashes completely and prints no stdout.
                if not res.stdout.strip():
                    log.error(
                        "Pylint returned no stdout",
                        extra={
                            "event": "pylint_no_stdout",
                            "stderr": res.stderr,
                            "exit_code": res.returncode
                        }
                    )
                    return []

                parsed = json.loads(res.stdout)
                for item in parsed:
                    pylint_type = item.get("type", "convention")
                    severity = map_severity(pylint_type, "pylint")

                    symbol = item.get("symbol", "linter-issue")
                    title = symbol.replace("-", " ").capitalize()

                    msg = item.get("message", "")
                    line = item.get("line")
                    explanation = f"Line {line}: {msg}" if line else msg

                    issues.append(Issue(
                        severity=severity,
                        title=title,
                        explanation=explanation,
                        fix=None
                    ))
            except subprocess.TimeoutExpired:
                log.error(
                    "Pylint subprocess timed out after 5 seconds",
                    extra={"event": "pylint_timeout", "timeout": 5}
                )
            except Exception as exc:
                log.error(
                    "Pylint execution failed",
                    exc_info=True,
                    extra={"event": "pylint_failed", "error": str(exc)}
                )

        elif language == "javascript":
            # Write JS code to a temp file
            code_file = tmp_path / "snippet.js"
            code_file.write_text(code, encoding="utf-8")

            # Write a minimal flat eslint.config.js to the temp directory
            config_file = tmp_path / "eslint.config.js"
            config_content = """
export default [
  {
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: {
        console: "readonly",
        window: "readonly",
        document: "readonly",
        process: "readonly",
        setTimeout: "readonly",
        setInterval: "readonly",
        clearTimeout: "readonly",
        clearInterval: "readonly",
        fetch: "readonly"
      }
    },
    rules: {
      "no-unused-vars": "warn",
      "no-undef": "error",
      "eqeqeq": "warn",
      "semi": ["warn", "always"],
      "no-var": "warn"
    }
  }
];
"""
            config_file.write_text(config_content, encoding="utf-8")

            try:
                # Run eslint
                cmd = ["npx", "-y", "eslint", "--no-config-lookup", "-c", "eslint.config.js", "--format=json", "snippet.js"]
                res = subprocess.run(cmd, capture_output=True, text=True, timeout=5, shell=False, cwd=tmpdir)

                if not res.stdout.strip():
                    log.error(
                        "ESLint returned no stdout",
                        extra={
                            "event": "eslint_no_stdout",
                            "stderr": res.stderr,
                            "exit_code": res.returncode
                        }
                    )
                    return []

                parsed = json.loads(res.stdout)
                # ESLint returns a list of results per file
                if parsed and isinstance(parsed, list):
                    file_res = parsed[0]
                    messages = file_res.get("messages", [])
                    for msg in messages:
                        eslint_severity = msg.get("severity", 1)
                        severity = map_severity(str(eslint_severity), "eslint")

                        rule_id = msg.get("ruleId")
                        title = rule_id.replace("-", " ").capitalize() if rule_id else "Linter issue"

                        explanation = msg.get("message", "JavaScript linter message")
                        line = msg.get("line")
                        if line:
                            explanation = f"Line {line}: {explanation}"

                        issues.append(Issue(
                            severity=severity,
                            title=title,
                            explanation=explanation,
                            fix=None
                        ))
            except subprocess.TimeoutExpired:
                log.error(
                    "ESLint subprocess timed out after 5 seconds",
                    extra={"event": "eslint_timeout", "timeout": 5}
                )
            except Exception as exc:
                log.error(
                    "ESLint execution failed",
                    exc_info=True,
                    extra={"event": "eslint_failed", "error": str(exc)}
                )

    return issues


# ---------------------------------------------------------------------------
# Health check
# ---------------------------------------------------------------------------

@app.get("/health", tags=["ops"])
async def health() -> dict[str, str]:
    """Liveness probe — returns 200 when the server is up."""
    return {"status": "ok"}


# ---------------------------------------------------------------------------
# Review and Usage endpoints
# ---------------------------------------------------------------------------

@app.get("/api/usage", response_model=UsageResponse, tags=["usage"])
async def get_usage() -> UsageResponse:
    """Return the accumulated in-memory request and token usage statistics."""
    return UsageResponse(**_usage_stats)


@app.post("/api/review", response_model=ReviewResponse, tags=["review"])
async def review_code(request: ReviewRequest) -> ReviewResponse:
    """
    Submit a code snippet for review and receive structured feedback.

    The `source` field in the response indicates which engine produced the
    result: `"ai"` for the GitHub Models call, `"fallback"` for the real
    subprocess linter (used when the AI call fails for any reason).

    `TRIGGER_500` in the code body forces a 500 regardless of AI status —
    this is an explicit test hook for the frontend error path, not a normal
    failure mode.
    """
    # Generate correlation ID for tracking request lifecycle
    correlation_id = str(uuid.uuid4())[:8]
    correlation_id_var.set(correlation_id)

    _usage_stats["total_requests"] += 1

    # ── Input size validation ────────────────────────────────────────────────
    # Cap submitted code at 500 lines or 10,000 characters
    line_count = len(request.code.splitlines())
    char_count = len(request.code)
    if not validate_input_length(request.code):
        log.warning(
            "Code size validation failed; request rejected",
            extra={
                "event": "guardrail_size_rejection",
                "line_count": line_count,
                "char_count": char_count
            }
        )
        raise HTTPException(
            status_code=400,
            detail="Code exceeds the 500-line limit for this tool."
        )

    # ── Deliberate error test hook ────────────────────────────────────────────
    # Checked first, before any AI call, so it always fires.
    if "TRIGGER_500" in request.code:
        log.error(
            "TRIGGER_500 detected — raising deliberate 500",
            extra={"event": "simulated_server_error"}
        )
        raise HTTPException(status_code=500, detail="Simulated server error")

    log.info(
        "Received code review request",
        extra={
            "event": "review_request_received",
            "language": request.language,
            "line_count": line_count,
            "char_count": char_count
        }
    )

    # ── AI path ───────────────────────────────────────────────────────────────
    try:
        issues = await asyncio.to_thread(_call_ai, request.code, request.language)
        log.info(
            "AI review succeeded",
            extra={
                "event": "ai_review_success",
                "issues_count": len(issues)
            }
        )
        _usage_stats["ai_requests"] += 1
        return ReviewResponse(source="ai", issues=issues)

    except Exception as exc:  # noqa: BLE001
        # Any failure in the AI path (bad token, timeout, rate limit, network
        # error, malformed JSON, schema mismatch, validation error) falls
        # through to the real linter fallback.
        log.warning(
            "AI review failed — falling back to static analysis",
            exc_info=True,
            extra={
                "event": "ai_review_failed_fallback_triggered",
                "error_type": type(exc).__name__,
                "error_message": str(exc)
            }
        )

    # ── Fallback path ─────────────────────────────────────────────────────────
    # Run real linter subprocess (pylint/eslint)
    issues = await asyncio.to_thread(_fallback_issues, request.code, request.language)
    log.info(
        "Fallback review complete",
        extra={
            "event": "fallback_review_success",
            "issues_count": len(issues)
        }
    )
    _usage_stats["fallback_requests"] += 1
    return ReviewResponse(source="fallback", issues=issues)
